./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K1_1_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K1_2_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K1_3_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K1_4_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K2_1_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K2_2_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K2_4_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K2_3_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K3_1_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K3_2_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K3_3_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K3_4_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K4_1_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K4_2_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K4_4_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K4_3_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K5_2_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K5_3_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K5_1_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K5_4_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K6_1_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K6_3_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K6_2_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K7_2_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K7_1_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K7_3_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K6_4_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K7_4_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K8_3_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K8_2_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K9_2_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K8_1_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K8_4_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K9_4_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K9_1_f
./structure_histogram.pl ../a.structure/output_admix_indep/output_admix_indep_K9_3_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K1_1_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K1_2_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K1_3_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K1_4_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K2_1_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K2_2_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K2_4_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K2_3_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K3_1_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K3_2_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K3_3_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K3_4_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K4_1_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K4_2_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K4_4_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K4_3_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K5_1_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K5_2_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K5_4_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K5_3_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K6_1_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K6_3_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K6_4_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K6_2_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K7_3_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K7_1_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K7_2_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K7_4_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K8_3_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K8_2_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K8_4_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K8_1_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K9_4_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K9_1_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K9_2_f
./structure_histogram.pl ../a.structure/output_admix_corre/output_admix_corre_K9_3_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K1_4_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K1_2_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K1_1_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K1_3_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K2_4_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K2_2_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K2_3_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K2_1_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K3_1_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K3_4_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K3_3_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K3_2_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K4_1_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K4_3_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K4_4_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K4_2_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K5_3_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K5_1_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K5_4_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K5_2_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K6_1_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K6_2_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K6_4_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K7_1_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K6_3_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K7_4_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K7_2_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K7_3_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K8_4_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K9_3_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K9_2_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K8_1_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K8_3_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K8_2_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K9_1_f
./structure_histogram.pl ../a.structure/output_noadm_indep/output_noadm_indep_K9_4_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K1_1_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K1_3_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K1_2_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K1_4_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K2_1_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K2_4_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K2_2_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K2_3_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K3_4_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K3_3_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K3_1_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K3_2_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K4_4_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K4_1_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K4_2_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K4_3_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K5_1_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K5_3_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K5_4_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K5_2_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K6_1_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K6_3_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K6_2_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K6_4_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K7_4_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K7_2_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K7_1_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K7_3_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K8_4_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K8_2_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K8_1_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K8_3_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K9_3_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K9_1_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K9_4_f
./structure_histogram.pl ../a.structure/output_noadm_corre/output_noadm_corre_K9_2_f
